### ISSUE TITLE
Can not pass advanced connection parameters/vertica specific parameters

### ISSUE THREAD

**Issue by Saintbotto** [vertica/sqltools-vertica-driver#11]
There's does not appear to be a way to pass through advanced/vertica specific connection parameters like tlsmode=require.
![image](https://github.com/vertica/sqltools-vertica-driver/assets/6013304/d3080624-4c54-4e2e-980c-a08b83c24de1)

Other drivers have sections for driver specific options
MySQL
![image](https://github.com/vertica/sqltools-vertica-driver/assets/6013304/72988704-0bf1-4369-b623-924b26a64b26)
Postgres
![image](https://github.com/vertica/sqltools-vertica-driver/assets/6013304/85309d24-d752-43e9-87eb-779535271b97)
Snowflake
![image](https://github.com/vertica/sqltools-vertica-driver/assets/6013304/0d0f8827-2ad2-4206-be30-3aa1f9e61fca)

Intellij for reference allows customization of many such parameters
![image](https://github.com/vertica/sqltools-vertica-driver/assets/6013304/84aa289f-da2c-46ac-a5bd-dc101ff1f8bf)

**Comment by sitingren** [comment]
The enhancement is now in v0.0.3

**Comment by Saintbotto** [comment]
Works perfectly for us now, thank you!
